### ISSUE TITLE
test github actions for CI

### ISSUE THREAD

**Issue by tdowrick** [SciKit-Surgery/scikit-surgerycore#46]
Windows/Mac/Linux

**Comment by tdowrick** [comment]
@MattClarkson @thompson318 @mianasbat 

See https://github.com/UCL/scikit-surgerycore/blob/github-actions-tox/.github/workflows/pythonapp.yml for example config file to run tests on mac/windows/linux. If you go to the 'Actions' tab in the repo you can see the results of the run(s).

**Comment by thompson318** [comment]
Looks about right, thank you. It's good that it's using tox. I couldn't find the badges, but I assume they're somewhere. So if we can set them up, and deploy to PyPi, then remove travis.yml and gitlab.yml we've got a nicely migrated repository.

**Comment by tdowrick** [comment]
* I've added in PyPI deployment, and tested with release 0.6.2.
* The badge should be set up to work, but won't be visible until we merge to master, as it looks for the CI results from the master branch by default.
* travis and gitlab CI files removed.

I have used an API token, rather than username/password for authentication with PyPI, which is now the recommended method of authenticating it seems. The token is stored as a GitHub secret on the repo. It doesn't look like it is possible to share token between repos, so we will have to add it manually to other repos as we go along.

As a side note, I read that GitHub actions are only free for public repos - are we likely to put any private ones on GitHub, or will we be keeping those on Gitlab?

**Comment by thompson318** [comment]
My approach would be to only put public repos on github. If it's something you want to keep private then you might as well leave it on gitlab.

**Comment by thompson318** [comment]
Is this ready to be merged?

**Comment by tdowrick** [comment]
Yes - then we can check that the status badge is working properly, and if so, close the issue.

**Comment by thompson318** [comment]
I just reopened this for the coverage button. The coverage badge links to coveralls.io which was done with

after_success:
 - coveralls

in travis. The coverage badge still links to coveralls, but I don't think the workflow is setting it now? Is there a better way to report coverage with the github workflow?

**Comment by tdowrick** [comment]
I'll take a look

**Comment by tdowrick** [comment]
Doesn't seem like there is any straightforward way to do it. We'd have to generate the coverage report within tox, which requires a bit of fiddling to get working. I shall keep at it.

**Comment by thompson318** [comment]
What happens if you just run "coveralls" after tox? All the travis.yml was doing was 

coverage run -a --source ./sksurgerycore -m pytest -v -s ./tests/

coverage report -m

then coveralls

**Comment by tdowrick** [comment]
I think if you run it after tox it won't have access to the coverage report (which is run in tox), but I can check.

**Comment by tdowrick** [comment]
Turns out that does work fine:
https://github.com/UCL/scikit-surgerycore/tree/coverage
https://coveralls.io/builds/30574992

**Comment by thompson318** [comment]
Excellent, thank you. I did put coveralls in requirements-dev, so pip install coveralls may not be necessary, alternatively remove coveralls from requirements-dev.

**Comment by tdowrick** [comment]
Requirements-dev is only installed in the tox environment, so we need the coveralls import as well, but we can take it out of requirements-dev.

The alternative is to install requirements-dev in the script, but that seemed unnecessary just to get tox and coveralls.
